[paths]
blog = 'https://caffeinatedope.net/blog'
qr = 'https://caffeinatedope.net'
google = 'https://google.com'
github = 'https://github.com/caffeinatedope'

[behaviors]
default_page = "https://caffeinatedope.net/projects/ricochet"