apiVersion: v1
kind: Pod
metadata:
  name: buildkit
spec:
  containers:
    - name: rust
      image: rust:alpine
      command:
      - cat
      tty: true
    - name: buildkit
      image: moby/buildkit:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: registry-creds
          mountPath: /root/.docker
          readOnly: true
  volumes:
    - name: registry-creds
      secret:
        secretName: codeberg-regcred
        defaultMode: 0400
        items:
          - key: .dockerconfigjson
            path: config.json