kind: ConfigMap
apiVersion: v1
metadata:
  name: ricochet-configmap
  namespace: ricochet
data:
  creator: https://caffeinatedope.net/
  github: https://github.com/CaffeinatedOpe/ricochet
  awesome: https://caffeinatedope.net/awesome